### ISSUE TITLE
Tests failling

### ISSUE THREAD

**Issue by alexbw** [aigamedev/scikit-neuralnetwork#101]
Theano==0.7.0
pylearn2@5a21a96

```
======================================================================
ERROR: test_ValidationSet (sknn.tests.test_conv.TestConvolution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 74, in test_ValidationSet
    valid_size=0.5))
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 20, in _run
    nn.fit(a_in, a_out)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 202, in fit
    return super(Regressor, self)._fit(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 127, in _fit
    X, y = self._initialize(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 41, in _initialize
    return self._backend._initialize_impl(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/backend/pylearn2/mlp.py", line 248, in _initialize_impl
    random_state=self.random_state)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 2 layers, 512 inputs and 4 outputs.
sknn: DEBUG:   - Convl: Tanh       Output: (30, 14)   Channels: 4
sknn: DEBUG:   - Dense: Linear     Units:  4
sknn: DEBUG:
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_VerticalVerbose (sknn.tests.test_conv.TestConvolution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 59, in test_VerticalVerbose
    n_iter=1, verbose=1, valid_size=0.1))
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 20, in _run
    nn.fit(a_in, a_out)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 202, in fit
    return super(Regressor, self)._fit(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 127, in _fit
    X, y = self._initialize(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 41, in _initialize
    return self._backend._initialize_impl(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/backend/pylearn2/mlp.py", line 248, in _initialize_impl
    random_state=self.random_state)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 2 layers, 512 inputs and 4 outputs.
sknn: DEBUG:   - Convl: Sigmoid    Output: (17, 16)   Channels: 4
sknn: DEBUG:   - Dense: Linear     Units:  4
sknn: DEBUG:
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ValidationSet (sknn.tests.test_conv.TestConvolutionRGB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 74, in test_ValidationSet
    valid_size=0.5))
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 210, in _run
    nn.fit(a_in, a_out)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 202, in fit
    return super(Regressor, self)._fit(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 127, in _fit
    X, y = self._initialize(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 41, in _initialize
    return self._backend._initialize_impl(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/backend/pylearn2/mlp.py", line 248, in _initialize_impl
    random_state=self.random_state)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 2 layers, 512 inputs and 4 outputs.
sknn: DEBUG:   - Convl: Tanh       Output: (30, 14)   Channels: 4
sknn: DEBUG:   - Dense: Linear     Units:  4
sknn: DEBUG:
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_VerticalVerbose (sknn.tests.test_conv.TestConvolutionRGB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 59, in test_VerticalVerbose
    n_iter=1, verbose=1, valid_size=0.1))
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 210, in _run
    nn.fit(a_in, a_out)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 202, in fit
    return super(Regressor, self)._fit(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 127, in _fit
    X, y = self._initialize(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 41, in _initialize
    return self._backend._initialize_impl(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/backend/pylearn2/mlp.py", line 248, in _initialize_impl
    random_state=self.random_state)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 2 layers, 512 inputs and 4 outputs.
sknn: DEBUG:   - Convl: Sigmoid    Output: (17, 16)   Channels: 4
sknn: DEBUG:   - Dense: Linear     Units:  4
sknn: DEBUG:
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ValidationSet (sknn.tests.test_conv.TestSerializedNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 74, in test_ValidationSet
    valid_size=0.5))
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 244, in _run
    a_test = super(TestSerializedNetwork, self)._run(original, a_in)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 20, in _run
    nn.fit(a_in, a_out)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 202, in fit
    return super(Regressor, self)._fit(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 127, in _fit
    X, y = self._initialize(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 41, in _initialize
    return self._backend._initialize_impl(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/backend/pylearn2/mlp.py", line 248, in _initialize_impl
    random_state=self.random_state)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 2 layers, 512 inputs and 4 outputs.
sknn: DEBUG:   - Convl: Tanh       Output: (30, 14)   Channels: 4
sknn: DEBUG:   - Dense: Linear     Units:  4
sknn: DEBUG:
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_VerticalVerbose (sknn.tests.test_conv.TestSerializedNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 59, in test_VerticalVerbose
    n_iter=1, verbose=1, valid_size=0.1))
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 244, in _run
    a_test = super(TestSerializedNetwork, self)._run(original, a_in)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 20, in _run
    nn.fit(a_in, a_out)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 202, in fit
    return super(Regressor, self)._fit(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 127, in _fit
    X, y = self._initialize(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 41, in _initialize
    return self._backend._initialize_impl(X, y)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sknn/backend/pylearn2/mlp.py", line 248, in _initialize_impl
    random_state=self.random_state)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/Users/Alex/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 2 layers, 512 inputs and 4 outputs.
sknn: DEBUG:   - Convl: Sigmoid    Output: (17, 16)   Channels: 4
sknn: DEBUG:   - Dense: Linear     Units:  4
sknn: DEBUG:
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 195 tests in 104.927s
```

Any other info I can provide to help here?

**Comment by alexbw** [comment]
Note that the `bench_mnist.py sknn` example works, though.

**Comment by alexjc** [comment]
Is this from an installed version, presumably 0.3?  It seems to work on the build machines with Travic CI, though there hasn't been a commit recently...

**Comment by alexbw** [comment]
I've pip installed scikit-neuralnetwork and theano, and built pylearn2 from
source.

**Comment by alexjc** [comment]
OK, thanks. I can't look at it this week, nucl.ai is coming up... but hopefully late next week or the week after.
