### ISSUE TITLE
Random test failure for weighted samples

### ISSUE THREAD

**Issue by alexjc** [aigamedev/scikit-neuralnetwork#168]
```
======================================================================
FAIL: test_SingleOutputOne (sknn.tests.test_data.TestMaskedDataRegression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sknn/tests/test_data.py", line 111, in test_SingleOutputOne
    self.check(a_in, a_out, a_mask)
  File "sknn/tests/test_data.py", line 104, in check
    assert_true((abs(a_out - v_out).T * (1.0 - a_mask) > 2.5E-1).any())
nose.proxy.AssertionError: False is not true

-------------------- >> begin captured stdout << ---------------------
[[  2.23569385e-10   5.21778176e-11   1.93400185e-10   0.00000000e+00
    5.56532820e-10   1.31965550e-10   3.22308846e-12   0.00000000e+00]]
```

**Comment by alexjc** [comment]
This looks either platform or version related. Running locally with latest of everything on CPU, I get no errors at all in 100 runs.

**Comment by alexjc** [comment]
I think [4aa03a4] finally fixes this. It was a problem with tests being too aggressive in their assumptions.
