### ISSUE TITLE
Training diverged and returned NaN.

### ISSUE THREAD

**Issue by ChrisyehGone** [aigamedev/scikit-neuralnetwork#207]
Traceback (most recent call last):

  File "<ipython-input-11-28432d3247ee>", line 1, in <module>
    runfile('C:/Users/Chrisyeh/Documents/Python Scripts/my/DD/LasagneExample.py', wdir='C:/Users/Chrisyeh/Documents/Python Scripts/my/DD')

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/Chrisyeh/Documents/Python Scripts/my/DD/LasagneExample.py", line 61, in <module>
    nn.fit(np.array(X_train), np.array(y_train))

  File "C:\Anaconda2\lib\site-packages\sknn\mlp.py", line 300, in fit
    return super(Regressor, self)._fit(X, y, w)

  File "C:\Anaconda2\lib\site-packages\sknn\mlp.py", line 248, in _fit
    raise e

RuntimeError: Training diverged and returned NaN.

**Comment by alexjc** [comment]
The error message should give you a suggestion how to fix it by changing your parameters. Your setup choice caused it to blow up.
