### ISSUE TITLE
nn.fit after nn.predict_proba() returns an error

### ISSUE THREAD

**Issue by jimmyroyer** [aigamedev/scikit-neuralnetwork#209]
Hello, I saved my NN state use pickle. When I re-load it, and first predict_proba(), I cannot re fit the classifier afterward. I get the following message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\sknn\mlp.py", line 397, in fit
    return super(Classifier, self)._fit(X, yp, w)
  File "C:\Anaconda\lib\site-packages\sknn\mlp.py", line 239, in _fit
    self._train(X, y, w)
  File "C:\Anaconda\lib\site-packages\sknn\mlp.py", line 151, in _train
    avg_train_error = self._backend._train_impl(X, y, w)
  File "C:\Anaconda\lib\site-packages\sknn\backend\lasagne\mlp.py", line 340, in _train_impl
    return self._batch_impl(X, y, w, self.trainer, mode='train', output='.', shuffle=True)
  File "C:\Anaconda\lib\site-packages\sknn\backend\lasagne\mlp.py", line 323, in _batch_impl
    loss += processor(Xb, yb, wb if wb is not None else 1.0)
TypeError: 'NoneType' object is not callable

I think the problem is that the classifier is "is_initialized", but NN._backend.trainer is null. Is it possible to de-initialized the classifier after a predict_proba, or do we have to reload the parameters from pickle?

Thanks

**Comment by alexjc** [comment]
If you call predict then it does initialization for prediction, if you call fit, it does initialization for training. Either call fit or initialize yourself first?

**Comment by jimmyroyer** [comment]
Thank you for your answer. Is it possible to initialize for training within calling fit?
Thanks

**Comment by alexjc** [comment]
It may be easier to clone the classifier and use a copy for the first prediction.
