### ISSUE TITLE
How to install on MacBook?

### ISSUE THREAD

**Issue by ghost** [aigamedev/scikit-neuralnetwork#222]
I use the installation guide(Both A & B) in the docs, however several error will be found when I run "nosetests -v sknn".

## Error Info
test_TrainRandomOneEpoch (sknn.tests.test_types.TestFormatDeterminism) ... ERROR
test_FitAllTypes (sknn.tests.test_types.TestMemoryMap) ... ok
test_PredictAllTypes (sknn.tests.test_types.TestMemoryMap) ... ok
test_FitAllTypes (sknn.tests.test_types.TestPandasDataFrame) ... ok
test_PredictAllTypes (sknn.tests.test_types.TestPandasDataFrame) ... ok
test_FitFloat32 (sknn.tests.test_types.TestScipySparseMatrix) ... ERROR
test_FitFloat64 (sknn.tests.test_types.TestScipySparseMatrix) ... ERROR
test_FitHybrid (sknn.tests.test_types.TestScipySparseMatrix) ... ERROR
test_FitMutator (sknn.tests.test_types.TestScipySparseMatrix) ... ERROR
test_Predict32 (sknn.tests.test_types.TestScipySparseMatrix) ... ERROR
test_Predict64 (sknn.tests.test_types.TestScipySparseMatrix) ... ERROR

======================================================================
ERROR: test_TrainRandomOneEpoch (sknn.tests.test_types.TestFormatDeterminism)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/tests/test_types.py", line 160, in test_TrainRandomOneEpoch
    nn2._fit(X_s, y_s)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 239, in _fit
    self._train(X, y, w)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 151, in _train
    avg_train_error = self._backend._train_impl(X, y, w)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 338, in _train_impl
    return self._batch_impl(X, y, w, self.trainer, mode='train', output='.', shuffle=True)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 319, in _batch_impl
    for Xb, yb, wb, _ in self._iterate_data(self.batch_size, X, y, w, shuffle):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 308, in _iterate_data
    Xb, yb, wb = cast(X, excerpt), cast(y, excerpt), cast(w, excerpt)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 293, in cast
    array = array[indices]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/sparse/dok.py", line 140, in __getitem__
    raise TypeError('index must be a pair of integers or slices')
TypeError: index must be a pair of integers or slices
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 1 layers, 16 inputs and 16 outputs.
sknn: DEBUG:   - Dense: Linear     Units:  16  
sknn: DEBUG: 
sknn: INFO: Training on dataset of 8 samples with 256 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
    1          1.103e-01                 N/A            0.0s
sknn: DEBUG: 
sknn: INFO: Terminating after specified 1 total iterations.
sknn: INFO: Initializing neural network with 1 layers, 16 inputs and 16 outputs.
sknn: DEBUG:   - Dense: Linear     Units:  16  
sknn: DEBUG: 
sknn: INFO: Training on dataset of 8 samples with 16 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_FitFloat32 (sknn.tests.test_types.TestScipySparseMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/tests/test_types.py", line 39, in test_FitFloat32
    self.nn._fit(X, y)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 239, in _fit
    self._train(X, y, w)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 151, in _train
    avg_train_error = self._backend._train_impl(X, y, w)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 338, in _train_impl
    return self._batch_impl(X, y, w, self.trainer, mode='train', output='.', shuffle=True)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 319, in _batch_impl
    for Xb, yb, wb, _ in self._iterate_data(self.batch_size, X, y, w, shuffle):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 308, in _iterate_data
    Xb, yb, wb = cast(X, excerpt), cast(y, excerpt), cast(w, excerpt)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 293, in cast
    array = array[indices]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/sparse/dok.py", line 140, in __getitem__
    raise TypeError('index must be a pair of integers or slices')
TypeError: index must be a pair of integers or slices
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 1 layers, 4 inputs and 4 outputs.
sknn: DEBUG:   - Dense: Linear     Units:  4   
sknn: DEBUG: 
sknn: INFO: Training on dataset of 8 samples with 0 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
    1          0.000e+00                 N/A            0.0s
sknn: DEBUG: 
sknn: INFO: Terminating after specified 1 total iterations.
sknn: INFO: Training on dataset of 8 samples with 0 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
    1          0.000e+00                 N/A            0.0s
sknn: DEBUG: 
sknn: INFO: Terminating after specified 1 total iterations.
sknn: INFO: Training on dataset of 8 samples with 0 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_FitFloat64 (sknn.tests.test_types.TestScipySparseMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/tests/test_types.py", line 32, in test_FitFloat64
    self.nn._fit(X, y)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 239, in _fit
    self._train(X, y, w)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 151, in _train
    avg_train_error = self._backend._train_impl(X, y, w)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 338, in _train_impl
    return self._batch_impl(X, y, w, self.trainer, mode='train', output='.', shuffle=True)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 319, in _batch_impl
    for Xb, yb, wb, _ in self._iterate_data(self.batch_size, X, y, w, shuffle):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 308, in _iterate_data
    Xb, yb, wb = cast(X, excerpt), cast(y, excerpt), cast(w, excerpt)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 293, in cast
    array = array[indices]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/sparse/dok.py", line 140, in __getitem__
    raise TypeError('index must be a pair of integers or slices')
TypeError: index must be a pair of integers or slices
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 1 layers, 4 inputs and 4 outputs.
sknn: DEBUG:   - Dense: Linear     Units:  4   
sknn: DEBUG: 
sknn: INFO: Training on dataset of 8 samples with 0 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
    1          0.000e+00                 N/A            0.0s
sknn: DEBUG: 
sknn: INFO: Terminating after specified 1 total iterations.
sknn: INFO: Training on dataset of 8 samples with 0 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
    1          0.000e+00                 N/A            0.0s
sknn: DEBUG: 
sknn: INFO: Terminating after specified 1 total iterations.
sknn: INFO: Training on dataset of 8 samples with 0 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_FitHybrid (sknn.tests.test_types.TestScipySparseMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/tests/test_types.py", line 46, in test_FitHybrid
    self.nn._fit(X, y)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 239, in _fit
    self._train(X, y, w)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 151, in _train
    avg_train_error = self._backend._train_impl(X, y, w)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 338, in _train_impl
    return self._batch_impl(X, y, w, self.trainer, mode='train', output='.', shuffle=True)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 319, in _batch_impl
    for Xb, yb, wb, _ in self._iterate_data(self.batch_size, X, y, w, shuffle):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 308, in _iterate_data
    Xb, yb, wb = cast(X, excerpt), cast(y, excerpt), cast(w, excerpt)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 293, in cast
    array = array[indices]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/sparse/dok.py", line 140, in __getitem__
    raise TypeError('index must be a pair of integers or slices')
TypeError: index must be a pair of integers or slices
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 1 layers, 4 inputs and 4 outputs.
sknn: DEBUG:   - Dense: Linear     Units:  4   
sknn: DEBUG: 
sknn: INFO: Training on dataset of 8 samples with 32 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
    1          0.000e+00                 N/A            0.0s
sknn: DEBUG: 
sknn: INFO: Terminating after specified 1 total iterations.
sknn: INFO: Training on dataset of 8 samples with 32 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
    1          0.000e+00                 N/A            0.0s
sknn: DEBUG: 
sknn: INFO: Terminating after specified 1 total iterations.
sknn: INFO: Training on dataset of 8 samples with 32 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_FitMutator (sknn.tests.test_types.TestScipySparseMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/tests/test_types.py", line 61, in test_FitMutator
    self.nn._fit(X, y)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 239, in _fit
    self._train(X, y, w)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 151, in _train
    avg_train_error = self._backend._train_impl(X, y, w)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 338, in _train_impl
    return self._batch_impl(X, y, w, self.trainer, mode='train', output='.', shuffle=True)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 319, in _batch_impl
    for Xb, yb, wb, _ in self._iterate_data(self.batch_size, X, y, w, shuffle):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 308, in _iterate_data
    Xb, yb, wb = cast(X, excerpt), cast(y, excerpt), cast(w, excerpt)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 293, in cast
    array = array[indices]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/sparse/dok.py", line 140, in __getitem__
    raise TypeError('index must be a pair of integers or slices')
TypeError: index must be a pair of integers or slices
-------------------- >> begin captured logging << --------------------
sknn: INFO: Initializing neural network with 1 layers, 4 inputs and 4 outputs.
sknn: DEBUG:   - Dense: Linear     Units:  4   
sknn: DEBUG: 
sknn: INFO: Training on dataset of 8 samples with 32 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
    1          1.037e-01                 N/A            0.0s
sknn: DEBUG: 
sknn: INFO: Terminating after specified 1 total iterations.
sknn: INFO: Training on dataset of 8 samples with 32 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
    1          8.827e-02                 N/A            0.0s
sknn: DEBUG: 
sknn: INFO: Terminating after specified 1 total iterations.
sknn: INFO: Training on dataset of 8 samples with 32 total size.
sknn: DEBUG:   - Terminating loop after 1 total iterations.
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_Predict32 (sknn.tests.test_types.TestScipySparseMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/tests/test_types.py", line 77, in test_Predict32
    yp = self.nn._predict(X)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 262, in _predict
    return self._backend._predict_impl(X)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 273, in _predict_impl
    for Xb, _, _, idx  in self._iterate_data(self.batch_size, X, y, shuffle=False):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 308, in _iterate_data
    Xb, yb, wb = cast(X, excerpt), cast(y, excerpt), cast(w, excerpt)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 293, in cast
    array = array[indices]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/sparse/dok.py", line 140, in __getitem__
    raise TypeError('index must be a pair of integers or slices')
TypeError: index must be a pair of integers or slices
-------------------- >> begin captured logging << --------------------
sknn: WARNING: WARNING: Computing estimates with an untrained network.
sknn: INFO: Initializing neural network with 1 layers, 4 inputs and 4 outputs.
sknn: DEBUG:   - Dense: Linear     Units:  4   
sknn: DEBUG: 
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_Predict64 (sknn.tests.test_types.TestScipySparseMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/tests/test_types.py", line 69, in test_Predict64
    yp = self.nn._predict(X)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/mlp.py", line 262, in _predict
    return self._backend._predict_impl(X)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 273, in _predict_impl
    for Xb, _, _, idx  in self._iterate_data(self.batch_size, X, y, shuffle=False):
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 308, in _iterate_data
    Xb, yb, wb = cast(X, excerpt), cast(y, excerpt), cast(w, excerpt)
  File "/Users/shao/Documents/scikit-neuralnetwork/sknn/backend/lasagne/mlp.py", line 293, in cast
    array = array[indices]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/sparse/dok.py", line 140, in __getitem__
    raise TypeError('index must be a pair of integers or slices')
TypeError: index must be a pair of integers or slices
-------------------- >> begin captured logging << --------------------
sknn: WARNING: WARNING: Computing estimates with an untrained network.
sknn: INFO: Initializing neural network with 1 layers, 4 inputs and 4 outputs.
sknn: DEBUG:   - Dense: Linear     Units:  4   
sknn: DEBUG: 
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 247 tests in 185.741s

FAILED (SKIP=10, errors=7)

**Comment by ghost** [comment]
Manual install steps:
sudo pip install scikit-learn==0.17
sudo pip install scipy==0.17.0
sudo pip install Theano==0.8.1
sudo pip install git+https://github.com/Lasagne/Lasagne.git@0440814#egg=Lasagne==0.2-dev
sudo pip install  -U numpy
git clone https://github.com/aigamedev/scikit-neuralnetwork.git
cd scikit-neuralnetwork
sudo python setup.py develop

**Comment by chenjxthu** [comment]
I met a same situation as you. Have you ever solved it?
