### ISSUE TITLE
Help Wanted! ModuleNotFoundError: No module named 'sklearn.cross_validation'

### ISSUE THREAD

**Issue by marctheshark3** [aigamedev/scikit-neuralnetwork#240]
#### for the test it gives me these errors: 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sknn/tests/__init__.py", line 1, in <module>
    from sknn.backend import lasagne
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sknn/backend/lasagne/__init__.py", line 5, in <module>
    from .mlp import MultiLayerPerceptronBackend
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sknn/backend/lasagne/mlp.py", line 22, in <module>
    import sklearn.cross_validation
ModuleNotFoundError: No module named 'sklearn.cross_validation'

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=2)

## So if someone could help me out so I can use scikit-neuralnetwork.

Thank you!

**Comment by Matt2843** [comment]
Hi! I think that the sklearn.cross_validation module is deprecated, and replaced by the sklearn.model_selection module in the newer scikit-learn versions, you could create a pull-request after correcting this in mlp.py.

**Comment by DarquesM** [comment]
Same problem here : 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-3a4cfc932009> in <module>
----> 1 from sknn.mlp import Regressor, Layer

D:\ProgramData\Anaconda3\lib\site-packages\sknn\mlp.py in <module>
     20 import sklearn.pipeline
     21 import sklearn.preprocessing
---> 22 import sklearn.cross_validation
     23 
     24 from .nn import NeuralNetwork, Layer, Convolution, Native, ansi

ModuleNotFoundError: No module named 'sklearn.cross_validation'

**Comment by sophieclayton** [comment]
I have the same issue:

(soph_py3) slocum:analysis sclayton$ nosetests -v sknn
ERROR
Failure: ModuleNotFoundError (No module named 'sklearn.cross_validation') ... ERROR

======================================================================
ERROR: test suite for <module 'sknn.backend' from '/miniconda2/envs/soph_py3/lib/python3.7/site-packages/sknn/backend/__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/sknn/backend/__init__.py", line 24, in setup
    from . import lasagne
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/sknn/backend/lasagne/__init__.py", line 5, in <module>
    from .mlp import MultiLayerPerceptronBackend
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/sknn/backend/lasagne/mlp.py", line 22, in <module>
    import sklearn.cross_validation
ModuleNotFoundError: No module named 'sklearn.cross_validation'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'sklearn.cross_validation')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/miniconda2/envs/soph_py3/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/miniconda2/envs/soph_py3/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/sknn/tests/__init__.py", line 1, in <module>
    from sknn.backend import lasagne
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/sknn/backend/lasagne/__init__.py", line 5, in <module>
    from .mlp import MultiLayerPerceptronBackend
  File "/miniconda2/envs/soph_py3/lib/python3.7/site-packages/sknn/backend/lasagne/mlp.py", line 22, in <module>
    import sklearn.cross_validation
ModuleNotFoundError: No module named 'sklearn.cross_validation


----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=2)

**Comment by hundanLi** [comment]
@sophieclayton It works for me. Thank you!
