### ISSUE TITLE
IndexError in topo_view_to_design_mat

### ISSUE THREAD

**Issue by matthiasplappert** [aigamedev/scikit-neuralnetwork#60]
I'm trying to use a very simple NN with a convolution layer to learn handwritten digits. Here's my code:

```
import sys
import logging

from sklearn.datasets import load_digits
from sklearn.cross_validation import StratifiedKFold
from sknn.mlp import Classifier, Layer, Convolution

logging.basicConfig(format="%(message)s", level=logging.DEBUG, stream=sys.stdout)

digits = load_digits()
X = digits.images
y = digits.target
print(X.shape, y.shape)  # outputs: ((1797, 8, 8), (1797,))

kf = StratifiedKFold(y, n_folds=3)
for train, test in kf:
    X_train, y_train = X[train], y[train]
    X_test, y_test = X[test], y[test]

    nn = Classifier(
        layers=[
            Convolution('Rectifier', channels=8, kernel_shape=(3, 3)),
            Layer('Softmax')],
        learning_rate=0.001,
        n_iter=25, verbose=1)
    nn.fit(X_train, y_train)
    print nn.score(X_test, y_test)
```

When training the network, I get the following error:
```
Traceback (most recent call last):
  File "/Users/matze/Labs/deeplearn/src/digits.py", line 29, in <module>
    nn.fit(X_train, y_train)
  File "/Users/matze/Labs/deeplearn/lib/python2.7/site-packages/sknn/mlp.py", line 839, in fit
    return super(Classifier, self)._fit(X, yp, test=y)
  File "/Users/matze/Labs/deeplearn/lib/python2.7/site-packages/sknn/mlp.py", line 696, in _fit
    X = self.ds.view_converter.topo_view_to_design_mat(X)
  File "/Users/matze/Labs/deeplearn/lib/python2.7/site-packages/sknn/pylearn2/datasets/dense_design_matrix.py", line 1396, in topo_view_to_design_mat
    if topo_array.shape[self.axes.index(axis)] != shape_elem:
IndexError: tuple index out of range
```

I have used neural network before but I'm very new to the idea of convolution. It is therefore perfectly possible that I'm trying doing something very stupid here. I've played around with the `kernel_shape` and `channels` values, but no luck. Any help or input on this would be greatly appreciated.

**Comment by alexjc** [comment]
I saw something similar but it was a problem in sklearn... Try this before you fit:
```
y.reshape((y.shape[0], 1))
```
If that's it I can add a simple fix for this...

**Comment by matthiasplappert** [comment]
I've tried to reshape both `y_train` and `y_test`–no luck, the same problem still occurs. I've also added a print statement to outer `for` loop in `topo_view_to_design_mat`: `print topo_array.shape, self.axes.index(axis)`. The output is as follows:

```
(1195, 8, 8, 8) 1
(1195, 8, 8, 8) 2
(1195, 8, 8, 8) 3
Initializing neural network with 2 layers, 64 inputs and 10 outputs.
('pylearn2 detector_space', [6, 6])
('pylearn2 output_space', (6, 6))
  - Convl: Rectifier  Output: (6, 6)     Channels: 8
  - Dense: Softmax    Units:  10  

(1195, 8, 8) 1
(1195, 8, 8) 2
(1195, 8, 8) 3

Traceback (most recent call last):
  File "/Users/matze/Labs/deeplearn/src/digits.py", line 34, in <module>
    nn.fit(X_train, y_train)
  File "/Users/matze/Labs/deeplearn/lib/python2.7/site-packages/sknn/mlp.py", line 839, in fit
    return super(Classifier, self)._fit(X, yp, test=y)
  File "/Users/matze/Labs/deeplearn/lib/python2.7/site-packages/sknn/mlp.py", line 696, in _fit
    X = self.ds.view_converter.topo_view_to_design_mat(X)
  File "/Users/matze/Labs/deeplearn/lib/python2.7/site-packages/sknn/pylearn2/datasets/dense_design_matrix.py", line 1397, in topo_view_to_design_mat
    if topo_array.shape[self.axes.index(axis)] != shape_elem:
IndexError: tuple index out of range
```

Interestingly, it seems to work fine in a first call (see output before the pylearn2 log stuff).

It should be rather easy to reproduce this issue with my code from the first post.

**Comment by alexjc** [comment]
This line fixes it:
```
X = digits.images.reshape((1797, 8, 8, 1))
```
I will add a test for that in the code and fix it next...

**Comment by matthiasplappert** [comment]
Sweet, thanks a lot!

**Comment by alexjc** [comment]
I added an example in the `digits` branch, but a few more tests are needed to make sure I didn't break anything important :-)

**Comment by alexjc** [comment]
OK, this and other similar conversions are now done automatically.
