### ISSUE TITLE
Saving Convolution layers through pickle doesn't work

### ISSUE THREAD

**Issue by TyxTyxyc** [aigamedev/scikit-neuralnetwork#67]
Hello!
First of all: thank you for sknn!

I've started to use sknn, and encountered some problems.
First one: I wasn't able to save `sknn.mlp` with pickle if `sknn.mlp` contains convolutional layers.
Here's some code: https://github.com/TyxTyxyc/playground/blob/master/sknn_pickle_save_bug.py.
It appears with `cPickle` and `pickle` module alike.

However, saving nets without convolutional layers works. Example code here: https://github.com/TyxTyxyc/playground/blob/master/sknn_pickle_save_bug_2.py

Some output for `sknn_pickle_save_bug.py`:
```
Initializing neural network with 4 layers, 64 inputs and 10 outputs.
  - Convl: Rectifier  Output: (10, 10)   Channels: 12
  - Convl: Rectifier  Output: (8, 8)     Channels: 8
  - Dense: Rectifier  Units:  128 
  - Dense: Softmax    Units:  10  

Training on dataset of 1,437 samples with 106,338 total size.
  - Reshaping input array from (1437, 8, 8) to (1293, 8, 8, 1).
  - Train: 1,293      Valid: 144 
  - Terminating loop after 10 total iterations.
  - Early termination after 10 stable iterations.

Epoch    Validation Error    Time
---------------------------------
    1        2.301751        3.5s
    2        2.302129        0.7s
    3        2.302112        0.7s
    4        2.301825        0.7s
    5        2.301359        0.7s
    6        2.302563        0.7s
    7        2.302163        0.7s
    8        2.302140        0.7s
    9        2.301912        0.7s
   10        2.302340        0.7s

Early termination condition fired at 10 iterations.

Traceback (most recent call last):
  File "/home/tyxtyx2/work/playground/sknn_pickle_save_bug.py", line 58, in <module>
    pickle.dump(net, outfile)
  File "/usr/lib64/python2.7/copy_reg.py", line 84, in _reduce_ex
    dict = getstate()
  File "/usr/lib64/python2.7/site-packages/sknn/mlp.py", line 309, in __getstate__
    d['weights'] = self._mlp_to_array()
  File "/usr/lib64/python2.7/site-packages/sknn/mlp.py", line 317, in _mlp_to_array
    return [(l.get_weights(), l.get_biases()) for l in self.mlp.layers]
  File "/usr/lib64/python2.7/site-packages/sknn/pylearn2/models/model.py", line 254, in get_weights
    raise NotImplementedError(str(type(self)) + " does not implement "
NotImplementedError: <class 'pylearn2.models.mlp.ConvElemwise'> does not implement get_weights (perhaps by design)

Process finished with exit code 1
```

**Comment by alexjc** [comment]
Thanks for the report! It definitely looks like a bug :-) Tagging for later...
