### ISSUE TITLE
Pooling doesn't work

### ISSUE THREAD

**Issue by TyxTyxyc** [aigamedev/scikit-neuralnetwork#68]
Hello again!

I've encountered another problem with convolutional layers. When I'm trying to set `pool_shape` parameter for `Convolution`, I get this error.
Might be a problem with Theano, according to comments in `theano/tensor/nnet/conv.py` in `ConvOp.grad`: something about bug in computations using that method.

Some code: https://github.com/TyxTyxyc/playground/blob/master/sknn_pooling_bug.py
And traceback:
```
Initializing neural network with 3 layers, 64 inputs and 10 outputs.
  - Convl: Rectifier  Output: (3, 3)     Channels: 8
  - Dense: Rectifier  Units:  128 
  - Dense: Softmax    Units:  10  

Traceback (most recent call last):
  File "/home/tyxtyx2/work/poker-vision/bugs.py", line 46, in <module>
    net.fit(X_train, y_train)
  File "/usr/lib64/python2.7/site-packages/sknn/mlp.py", line 480, in fit
    return super(Classifier, self)._fit(X, yp, test=y)
  File "/usr/lib64/python2.7/site-packages/sknn/mlp.py", line 344, in _fit
    return self._train(*data, **extra)
  File "/usr/lib64/python2.7/site-packages/sknn/mlp.py", line 362, in _train
    self._initialize(X, y)
  File "/usr/lib64/python2.7/site-packages/sknn/mlp.py", line 296, in _initialize
    self.trainer.setup(self.mlp, self.ds)
  File "/usr/lib64/python2.7/site-packages/sknn/pylearn2/training_algorithms/sgd.py", line 330, in setup
    ** fixed_var_descr.fixed_vars)
  File "/usr/lib64/python2.7/site-packages/sknn/pylearn2/costs/cost.py", line 162, in get_gradients
    grads = T.grad(cost, params, disconnected_inputs='ignore')
  File "/usr/lib64/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gradient.py", line 545, in grad
    grad_dict, wrt, cost_name)
  File "/usr/lib64/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gradient.py", line 1283, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/usr/lib64/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gradient.py", line 1241, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/usr/lib64/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gradient.py", line 1089, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)
  File "/usr/lib64/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/nnet/conv.py", line 850, in grad
    raise Exception("ConvOp.grad when dx!=1 or dy!=1 we must have all "
Exception: ConvOp.grad when dx!=1 or dy!=1 we must have all the optional shape information

Process finished with exit code 1
```
Still investigating source code (slowly, in fact, due to lack of expirience), might provide some additional info later.

**Comment by alexjc** [comment]
There are a lot of convolution tests in `test_conv.py` maybe that can help isolate the problem, or find a syntax/parameter combination that works.

I'll try and take a look along with the other bugs too.

**Comment by TyxTyxyc** [comment]
Some updates.
I've run all the tests, everything was OK. But I've found that these options (assuming that other code identical to https://github.com/TyxTyxyc/playground/blob/master/sknn_pooling_bug.py):
```python
conv_layer_1 = Convolution(
    ...
    border_mode='full',
    pool_shape=(2, 2)
    )
```
will cause the bug, and these:
```python
conv_layer_1=Convolution(
    ...
    # border_mode='full',
    pool_shape=(2, 2)
    )
```
wouldn't. Also, disabling all unnessesary options in `Classifier` or `Regressor` won't help with that error.
That's strange, because my system can pass `test_SquarePoolFull`, I've checked it twice.

**Comment by alexjc** [comment]
OK, thanks for the update! Try a `(3,3)` shape or the same as the test?

**Comment by TyxTyxyc** [comment]
Yes, when I try any shape other than `(2, 2)` (like `(3, 3), (3, 4), (2, 3)`), it still doesn't work, but output is different:
```
Traceback (most recent call last):
  File "/home/tyxtyx2/work/playground/sknn_pooling_bug.py", line 161, in <module>
    net.fit(ims, keys)
  File "/usr/lib64/python2.7/site-packages/sknn/mlp.py", line 480, in fit
    return super(Classifier, self)._fit(X, yp, test=y)
  File "/usr/lib64/python2.7/site-packages/sknn/mlp.py", line 353, in _fit
    raise e
NotImplementedError: ERROR: We disable ConvOp.grad now when dx or dy are different from 1 and 2, as there is a bug in it.

A runtime exception was caught during training. This likely occurred due to
a divergence of the SGD algorithm, and NaN floats were found by PyLearn2.

Try setting the `learning_rate` 10x lower to resolve this, for example:
    learning_rate=0.000000
```
For this output, `learning_rate=0.0000003`

**Comment by alexjc** [comment]
First, your batch_size may need to be set to 1 because there's a weird number of training samples and Theano complains.  Also, while `border_mode='valid'` works, getting pooling right seems difficult in `full` mode... the ideal would be to have a `border_mode='same'` as per #33.

**Comment by alexjc** [comment]
I think there might be a bug on our side for the `full` support, looking at this a bit later.

**Comment by alexjc** [comment]
Not sure I know how to fix the remaining bug. @ssamot?

```
Traceback (most recent call last):
  File "bug.py", line 50, in <module>
    net.fit(X_train, y_train)
  File "sknn/mlp.py", line 487, in fit
    return super(Classifier, self)._fit(X, yp, test=y)
  File "sknn/mlp.py", line 351, in _fit
    return self._train(*data, **extra)
  File "sknn/mlp.py", line 394, in _train
    self._train_layer(self.trainer, self.mlp, self.ds)
  File "sknn/nn.py", line 504, in _train_layer
    trainer.train(dataset=dataset)
  File "pylearn2/training_algorithms/sgd.py", line 455, in train
    self.sgd_update(*batch)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[2] = 5, input[1].shape[2] = 4)
Apply node that caused the error: Elemwise{add,no_inplace}(ConvOp{('imshp', (1, 8, 8)),('kshp', (3, 3)),('nkern', 8),('bsize', 1),('dx', 2),('dy', 2),('out_mode', 'full'),('unroll_batch', 1),('unroll_kern', 4),('unroll_patch', False),('imshp_logical', (1, 8, 8)),('kshp_logical', (3, 3)),('kshp_logical_top_aligned', True)}.0, DimShuffle{x,0,1,2}.0)
Inputs types: [TensorType(float64, 4D), TensorType(float64, (True, False, False, False))]
Inputs shapes: [(1, 8, 5, 5), (1, 8, 4, 4)]
Inputs strides: [(1600, 200, 40, 8), (1024, 128, 32, 8)]
Inputs values: ['not shown', 'not shown']

Backtrace when the node is created:
  File "pylearn2/models/mlp.py", line 3223, in fprop
    z = z + b
```

In general, it feels like an input space that's too small to use pooling... The tests use 32x32 and this is only 8x8.

**Comment by alexjc** [comment]
I started bumping into this more now I know there's a bug :-) But something is wrong with convolution, #63.

**Comment by ddofer** [comment]
Same issue. (I thought I had something wrong in my input initially).

**Comment by alexjc** [comment]
If you can find the bug you're doing better than me :-)
