### ISSUE TITLE
Error when running nosetest

### ISSUE THREAD

**Issue by zjyin** [aigamedev/scikit-neuralnetwork#85]
E................................................E.E.......E.E................................................................................................................
======================================================================
ERROR: Failure: ImportError (No module named pylearn2.utils.logger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/pylearn2/__init__.py", line 4, in <module>
    from pylearn2.utils.logger import configure_custom
ImportError: No module named pylearn2.utils.logger

======================================================================
ERROR: test_ValidationSet (sknn.tests.test_conv.TestConvolution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 69, in test_ValidationSet
    valid_size=0.5))
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 16, in _run
    nn.fit(a_in, a_out)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 434, in fit
    return super(Regressor, self)._fit(X, y)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 344, in _fit
    return self._train(*data, **extra)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 362, in _train
    self._initialize(X, y)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 281, in _initialize
    random_state=self.random_state)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2

======================================================================
ERROR: test_VerticalVerbose (sknn.tests.test_conv.TestConvolution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 54, in test_VerticalVerbose
    n_iter=1, verbose=1, valid_size=0.1))
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 16, in _run
    nn.fit(a_in, a_out)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 434, in fit
    return super(Regressor, self)._fit(X, y)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 344, in _fit
    return self._train(*data, **extra)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 362, in _train
    self._initialize(X, y)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 281, in _initialize
    random_state=self.random_state)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2

======================================================================
ERROR: test_ValidationSet (sknn.tests.test_conv.TestConvolutionRGB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 69, in test_ValidationSet
    valid_size=0.5))
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 205, in _run
    nn.fit(a_in, a_out)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 434, in fit
    return super(Regressor, self)._fit(X, y)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 344, in _fit
    return self._train(*data, **extra)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 362, in _train
    self._initialize(X, y)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 281, in _initialize
    random_state=self.random_state)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2

======================================================================
ERROR: test_VerticalVerbose (sknn.tests.test_conv.TestConvolutionRGB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 54, in test_VerticalVerbose
    n_iter=1, verbose=1, valid_size=0.1))
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/tests/test_conv.py", line 205, in _run
    nn.fit(a_in, a_out)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 434, in fit
    return super(Regressor, self)._fit(X, y)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 344, in _fit
    return self._train(*data, **extra)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 362, in _train
    self._initialize(X, y)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sknn/mlp.py", line 281, in _initialize
    random_state=self.random_state)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/home/zjyin/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2

----------------------------------------------------------------------
Ran 174 tests in 56.781s

**Comment by alexjc** [comment]
If you want to run the tests, I recommend you install PyLearn2 globally, see instructions on front page.  Then it should work as expected...

**Comment by alexjc** [comment]
It also seems you're running tests from the GitHub latest vs. the packaged SKNN?  I'm going to close this since you resolved it elsewhere. #83
